seer_124m:
  model:
    block_size: 1024 #Context windo
    vocab_size: 50257 #Vocab size from our tokenizer
    n_layer: 20 #Number of total blocks of attention and MLP
    n_head: 16 #Number of heads in multihead attention
    n_embd: 1024 #Embedding dimensions for our tokens
    dropout: 0.0 #Probability element is 0 out
    bias: True #Watn layers to include bias term

  train:
    learning_rate:
    min_lr:
    warmup_steps:
    max_steps:
    weight_decay:
    beta1:
    beta2:
    grad_clip:
    total_batch_size:
    micro_batch_size:
    block_size:
    eval_iterval:
    eval_iters:
    log_iterval:

system:
  device:
  dtype:
  compile:
  seed:
